# -*- coding: utf-8 -*-
"""422_task1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MEcekVzGxtusIbJ-DlUIiATVb0pm3xhf
"""

input = open('input 1.txt','r')
lines = input.readlines()

g_matrix = []
for line in lines:
    #print(line)
    g_matrix.append(line.split())

print(g_matrix)

rows = len(g_matrix)
print(rows)
coloumns = len(g_matrix[0])
print(coloumns)

visited = [[0]*len(g_matrix[0]) for _ in range(len(g_matrix))]

def checker(i,j,count,g_matrix,visited):

  if(i>-1 and i<rows and j>-1 and j<coloumns):
    
    #immediate up checker
    if((i-1)> -1):
      if(visited[i-1][j]==0 and g_matrix[i-1][j]=="Y"):
        visited[i-1][j] = 1
        count = checker(i-1,j,count,g_matrix,visited)
        count = count+1
    
    #immediate bottom checker
    if((i+1)<rows):
      if(visited[i+1][j]==0 and g_matrix[i+1][j]=="Y"):
        visited[i+1][j] = 1
        count = checker(i+1,j,count,g_matrix,visited)
        count = count+1

    #immediate left checker    
    if((j-1)> -1):
      if(visited[i][j-1]==0 and g_matrix[i][j-1]=="Y"):
        visited[i][j-1] = 1
        count = checker(i,j-1,count,g_matrix,visited)
        count = count+1

    #immediate right checker    
    if((j+1) < coloumns):
      if(visited[i][j+1]==0 and g_matrix[i][j+1]=="Y"):
        visited[i][j+1] = 1
        count = checker(i,j+1,count,g_matrix,visited)
        count = count+1

    #top left checker    
    if ((i-1)>-1 and (j-1)>-1):
      if(visited[i-1][j-1]==0 and g_matrix[i-1][j-1]=="Y"):
        visited[i-1][j-1] = 1
        count = checker(i-1,j-1,count,g_matrix,visited)
        count = count+1

    #top right checker    
    if ((i-1)>-1 and (j+1)<coloumns):
      if(visited[i-1][j+1]==0 and g_matrix[i-1][j+1]=="Y"):
        visited[i-1][j+1] = 1
        count = checker(i-1,j+1,count,g_matrix,visited)
        count = count+1

    #bottom left checker    
    if ((i+1)<rows and (j-1)>-1):
      if(visited[i+1][j-1]==0 and g_matrix[i+1][j-1]=="Y"):
        visited[i+1][j-1] = 1
        count = checker(i+1,j-1,count,g_matrix,visited)
        count = count+1

    #bottom right checker    
    if ((i+1)<rows and (j+1)<coloumns):
      if(visited[i+1][j+1]==0 and g_matrix[i+1][j+1]=="Y"):
        visited[i+1][j+1] = 1
        count = checker(i+1,j+1,count,g_matrix,visited)
        count = count+1
  return count

count_list = []
count = 0
for i in range(rows):
  for j in range(coloumns):
    if(visited[i][j] == 0 and g_matrix[i][j]=="Y"):
      visited[i][j] = 1
      count = checker(i,j,count,g_matrix,visited)
      count = count+1
      count_list.append(count)
  count = 0
print(max(count_list))